package com.example.eduworldbe.model;

public enum NotificationType {
  // For Students
  STUDENT_ADDED_TO_COURSE,
  JOIN_REQUEST_ACCEPTED,
  JOIN_REQUEST_REJECTED,
  SOLUTION_ACCEPTED,
  SOLUTION_REJECTED,
  POST_APPROVED,
  POST_REJECTED,
  COMMENT_ON_OWN_POST,
  NEW_LECTURE_IN_COURSE,
  NEW_EXAM_IN_COURSE,

  // For Teachers
  NEW_JOIN_REQUEST_FOR_TEACHER,
  NEW_SOLUTION_FOR_TEACHER_APPROVAL,
  NEW_POST_FOR_TEACHER_APPROVAL
}